### ISSUE TITLE
已经被360秒了

### ISSUE THREAD

**Issue by xiangyuanxuan** [huaigu4ng/SysWhispers3WinHttp#10]

**Comment by huaigu4ng** [comment]
还没吧，不过开源了迟早会被秒
![屏幕截图 2024-06-24 142234](https://github.com/huaigu4ng/SysWhispers3WinHttp/assets/128464183/ae1eede1-da8d-42cd-a2bc-bb8f8c8e580a)

**Comment by xiangyuanxuan** [comment]
现在连火绒静态都过不了了
![Uploading 17.png…]()

**Comment by xiangyuanxuan** [comment]
![17](https://github.com/huaigu4ng/SysWhispers3WinHttp/assets/34560197/44c5fd19-f0e5-476c-8586-63464ba078c3)
现在连火绒静态都过不了了
