### ISSUE TITLE
 (进程 35932)已退出，代码为 -1073741819

### ISSUE THREAD

**Issue by fgfxf** [huaigu4ng/SysWhispers3WinHttp#3]
(进程 35932)已退出，代码为 -1073741819
这个错误代码是0xC0000005的16进制表示，代表的是访问冲突异常，也就是说程序试图访问不属于它的内存地址，或者试图访问已经被释放的内存地址。这可能是由于指针错误、数组越界、使用未初始化的变量、内存泄漏等原因导致的。建议检查代码中是否存在这样的问题，并进行修正。

Process exited after 3.32 seconds with return value 3221225477
这个返回值 3221225477 是 0xC0000005 的十六进制表示，对应的是 Windows 操作系统的错误代码 STATUS_ACCESS_VIOLATION，即访问违规错误。

这种错误通常是由于访问了未分配的内存、已释放的内存或无效的内存地址而导致的。你可以检查你的程序中是否有这种错误，并使用调试工具或技巧进行诊断和修复，例如使用堆栈跟踪工具或内存分析工具来确定哪些代码导致了错误。

**Comment by fgfxf** [comment]
dwSize = 0;
WinHttpQueryDataAvailable(hRequest, &dwSize);
这里，返回值是0，应该改成循环接受直到为0。


	DWORD dwDownloaded = 0;
	if (bResults)
		do
		{
			dwSize = 4096;
			pszOutBuffer = (unsigned char*)calloc(dwSize + 1, sizeof(unsigned char));
			ZeroMemory(pszOutBuffer, dwSize + 1);
			WinHttpReadData(hRequest, (LPVOID)pszOutBuffer, dwSize, &dwDownloaded);
			VxMoveMemory((PVOID)hptr, pszOutBuffer, dwSize);
			hptr += dwDownloaded;
			free(pszOutBuffer);
		} while (dwDownloaded > 0);

**Comment by huaigu4ng** [comment]
1. WinHttp功能根据官方文档编写
![image](https://user-images.githubusercontent.com/128464183/235072182-8c75c56c-59c0-46c7-9d2e-15d5a11375ef.png)
2. WinHttpQueryDataAvailable函数返回的是可使用读取的数据量，默认为8KB
![image](https://user-images.githubusercontent.com/128464183/235068413-d1091410-19fe-4cff-8caa-d73ea6b1fa7f.png)
3.  WinHttpQueryDataAvailable函数返回值为0说明函数并未成功调用，可通过GetLastError函数获取错误代码，排查具体原因
![image](https://user-images.githubusercontent.com/128464183/235068320-3f8825a2-a0a2-497b-ac9d-32b71bc91b99.png)
