### ISSUE TITLE
ShowWindow(GetConsoleWindow(), SW_HIDE);

### ISSUE THREAD

**Issue by fgfxf** [huaigu4ng/SysWhispers3WinHttp#4]
ShowWindow(GetConsoleWindow(), SW_HIDE);
源代码是ShowWindow(GetForegroundWindow(), 0);，别逗我了

**Comment by huaigu4ng** [comment]
1. GetForegroundWindow函数是获取用户当前正在使用窗口的句柄
![image](https://user-images.githubusercontent.com/128464183/235067988-25325b99-c044-4b09-9617-a75c1de37a4a.png)
2. SW_HIDE值就是0
![image](https://user-images.githubusercontent.com/128464183/235067844-ebb5779a-15ff-475e-847e-312249aac214.png)
