### ISSUE TITLE
win7上不能跑吗？

### ISSUE THREAD

**Issue by Richard-Tang** [huaigu4ng/SysWhispers3WinHttp#6]
在MacOS上编译

`i686-w64-mingw32-gcc -o SysWhispers3WinHttp.exe syscalls.c SysWhispers3WinHttp.c -masm=intel -fpermissive -w -s -lwinhttp`

Windows7上运行

<img width="890" alt="image" src="https://github.com/huaigu4ng/SysWhispers3WinHttp/assets/30547741/99964e11-b9d4-4fa2-b180-7cc6ec20aeab">

Windows10上是能正常上线的，到Windows7就不行了。

```
OS 名称:          Microsoft Windows 7 专业版
OS 版本:          6.1.7601 Service Pack 1 Build 7601
```

**Comment by huaigu4ng** [comment]
SysWhispers3原项目仅测试了Windows10，目前还未测试过Windows7。
https://github.com/klezVirus/SysWhispers3#caveats-and-limitations
