### ISSUE TITLE
win10下好像报错了

### ISSUE THREAD

**Issue by qahehe** [huaigu4ng/SysWhispers3WinHttp#7]
![image](https://github.com/huaigu4ng/SysWhispers3WinHttp/assets/25258443/80ca5d42-2d1c-4f42-9404-bc9523d30153)
win10下编译成功，在物理机下执行错误，msf没有上线。用的readme里的windows mingw32编译器

**Comment by huaigu4ng** [comment]
推荐还是在Linux下编译
